"""add_token_prefix_to_refresh_tokens

Revision ID: fd83fa14d29f
Revises: 7e2d3738e035
Create Date: 2026-06-10 16:36:07.972958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd83fa14d29f'
down_revision: Union[str, Sequence[str], None] = '7e2d3738e035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_prefix', sa.String(length=16), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_token_prefix'), 'refresh_tokens', ['token_prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_prefix'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'token_prefix')
    # ### end Alembic commands ###
